services:
  kami-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kami-frontend
    restart: always
    ports:
      - "2323:2323"
    env_file:
      - .env
    networks:
      - kami-network

networks:
  kami-network:
    driver: bridge
